/**
 * Public receipt page: GET /functions/v1/receipt?token=... (the /r/{token} route in
 * docs/07 section 13 maps here).
 *
 * No login. The token is the whole credential, so the page is marked private and
 * noindex, and get_receipt() returns only what a customer should see - shop, amount,
 * time, reference. No customer identity, no balances, no internal ids.
 *
 * The page is served with the anon key: it can reach nothing except get_receipt, which is
 * the only function granted to anon.
 */
import { createClient } from "jsr:@supabase/supabase-js@2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;

interface Receipt {
  business_name: string;
  verified: boolean;
  amount_minor: number;
  occurred_at: string;
  reference: string | null;
  payer_app: string | null;
  reversed: boolean;
}

/** Tk with lakh grouping, matching formatMoney in packages/shared. */
function formatTaka(amountMinor: number): string {
  const taka = Math.trunc(Math.abs(amountMinor) / 100).toString();
  const last3 = taka.slice(-3);
  const rest = taka.slice(0, -3);
  const grouped = rest
    ? rest.replace(/\B(?=(\d{2})+(?!\d))/g, ",") + "," + last3
    : last3;
  return `Tk ${amountMinor < 0 ? "-" : ""}${grouped}`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function page(receipt: Receipt): string {
  const when = new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "Asia/Dhaka",
  }).format(new Date(receipt.occurred_at));

  // Bangla first, with the English line underneath, same as the app.
  return `<!doctype html>
<html lang="bn">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>রসিদ - ${escapeHtml(receipt.business_name)}</title>
<style>
  :root {
    --bg: #F7F8FA; --surface: #FFFFFF; --text: #111827; --muted: #5B6472;
    --good: #15803D; --good-bg: #DCFCE7; --bad: #B91C1C; --bad-bg: #FEE2E2;
    --divider: #E5E7EB;
  }
  @media (prefers-color-scheme: dark) {
    :root { --bg: #0B1220; --surface: #111A2E; --text: #F3F4F6; --muted: #9AA4B2; }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--bg); color: var(--text);
    font-family: "Hind Siliguri", "Noto Sans Bengali", system-ui, sans-serif;
    display: flex; justify-content: center; padding: 24px 16px;
  }
  main { width: 100%; max-width: 420px; background: var(--surface);
         border-radius: 20px; padding: 24px; }
  .shop { display: flex; align-items: center; gap: 8px; font-size: 18px; font-weight: 700; }
  .pill { display: inline-flex; align-items: center; gap: 4px; font-size: 13px;
          font-weight: 700; border-radius: 999px; padding: 4px 12px; }
  .pill.good { color: var(--good); background: var(--good-bg); }
  .pill.bad { color: var(--bad); background: var(--bad-bg); }
  .amount { font-size: 40px; font-weight: 700; margin: 16px 0 4px; }
  .muted { color: var(--muted); font-size: 14px; }
  dl { margin: 20px 0 0; border-top: 1px solid var(--divider); padding-top: 16px; }
  .row { display: flex; justify-content: space-between; gap: 16px; padding: 6px 0; }
  dt { color: var(--muted); font-size: 14px; margin: 0; }
  dd { margin: 0; font-size: 14px; }
</style>
</head>
<body>
<main>
  <div class="shop">
    <span>${escapeHtml(receipt.business_name)}</span>
    ${receipt.verified ? '<span class="pill good">v যাচাই করা</span>' : ""}
  </div>

  ${receipt.reversed ? '<p><span class="pill bad">! এই পেমেন্ট ফেরত হয়েছে</span></p>' : ""}

  <div class="amount">${formatTaka(receipt.amount_minor)}</div>
  <div class="muted">${escapeHtml(when)}</div>

  <dl>
    ${
      receipt.payer_app
        ? `<div class="row"><dt>যে অ্যাপ থেকে</dt><dd>${escapeHtml(receipt.payer_app)}</dd></div>`
        : ""
    }
    ${
      receipt.reference
        ? `<div class="row"><dt>রেফারেন্স</dt><dd>${escapeHtml(receipt.reference)}</dd></div>`
        : ""
    }
  </dl>

  <p class="muted">upay BizFlow থেকে তৈরি রসিদ / Receipt generated by upay BizFlow</p>
</main>
</body>
</html>`;
}

function notFound(): Response {
  return new Response(
    `<!doctype html><html lang="bn"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow"><title>রসিদ পাওয়া যায়নি</title></head>
<body style="font-family: system-ui, sans-serif; padding: 24px">
<p>এই রসিদটি পাওয়া যায়নি / This receipt could not be found.</p>
</body></html>`,
    {
      status: 404,
      headers: { "Content-Type": "text/html; charset=utf-8", "X-Robots-Tag": "noindex" },
    },
  );
}

Deno.serve(async (req) => {
  if (req.method !== "GET") {
    return new Response("Method not allowed", { status: 405 });
  }

  // Accept both ?token=... and a trailing /r/<token> style path.
  const url = new URL(req.url);
  const token =
    url.searchParams.get("token") ?? url.pathname.split("/").filter(Boolean).pop() ?? "";

  if (!/^[0-9a-f]{32}$/.test(token)) {
    return notFound();
  }

  const supabase = createClient(SUPABASE_URL, ANON_KEY, {
    auth: { persistSession: false },
  });

  const { data, error } = await supabase.rpc("get_receipt", { p_token: token });

  if (error || !data) {
    return notFound();
  }

  return new Response(page(data as Receipt), {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      // A receipt is for the person holding the link, so no shared cache and no indexing.
      "Cache-Control": "private, max-age=60",
      "X-Robots-Tag": "noindex",
      "Referrer-Policy": "no-referrer",
    },
  });
});
